### ISSUE TITLE
Check and test all the methods

### ISSUE THREAD

**Issue by izaharkin** [izaharkin/SplashGeom#1]
We want to have a stable library, so we need to test and chrck all the methods in library.

**Comment by flatplate** [comment]
Hello, I would like to help if you tell me how but I couldn't even find a readme file.

**Comment by izaharkin** [comment]
Wow, thanks, flatplate, but It`s only for my team, I`m just new at GitHub, so I didn`t know, that it work so :D
But thank you :)

**Comment by flatplate** [comment]
Oh sorry, good luck then :)

**Comment by izaharkin** [comment]
Thank you :)
